export const INIT_PREVIEWLIST = 'INIT_PREVIEW_LIST';
export const SET_TITLE = 'SET_TITLE';
export const SET_CONTENT = 'SET_CONTENT';
export const FETCH_PREVIEW_LOCAL_POST = 'FETCH_PREVIEW_LOCAL_POST';
export const UPDATE_LIMIT_PIVOT = 'UPDATE_LIMIT_PIVOT';
export const UPDATE_LAST_ID = 'UPDATE_LAST_ID';
