export const UPDATE_ANOTHER_USER = 'UPDATE_ANOTHER_USER';
export const INIT_SUBSCRIBE_LIST = 'INIT_SUBSCRIBE_LIST';
export const UPDATE_READER_LIST = 'UPDATE_READER_LIST';
export const UPDATE_REPORTER_LIST = 'UPDATE_REPORTER_LIST';
export const UPDATE_LOCAL_LIST = 'UPDATE_LOCAL_LIST';
export const UPDATE_IS_SUBSCRIBE = 'UPDATE_IS_SUBSCRIBE';
export const UPDATE_USER_RELIABILITY_SCORE = 'UPDATE_USER_RELIABILITY_SCORE';
