export const SET_COMMENT_CONTENT = 'SET_COMMENT_CONTENT';
export const INIT_COMMENT_DATA = 'INIT_COMMENT_DATA';
export const UPDATE_LAST_ID = 'UPDATE_LAST_ID';
export const FETCH_POST_LIST = 'FETCH_POST_LIST';
export const INIT_COMMENT_CONTENT = 'INIT_COMMENT_CONTENT';
