export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_PLACE_ID = 'UPDATE_PLACE_ID';
