export const SET_FOUND_ID = 'SET_FOUND_ID';
export const FIND_PASSWORD_SUCCESS = 'FIND_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const UPDATE_DETAIL_POST = 'UPDATE_DETAIL_POST;'
export const GET_REAL_NAME = 'GET_REAL_NAME';

